"""initial schema

Revision ID: 01206c72804c
Revises: 
Create Date: 2026-07-22 19:10:23.173752

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '01206c72804c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('classificacao', sa.String(length=30), nullable=False),
    sa.Column('limitacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('election',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Integer(), nullable=False),
    sa.Column('tipo_eleicao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'turno', 'tipo_eleicao', name='uq_election_ano_turno_tipo')
    )
    op.create_index(op.f('ix_election_ano'), 'election', ['ano'], unique=False)
    op.create_table('office',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('party',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla', 'numero', name='uq_party_sigla_numero')
    )
    op.create_index(op.f('ix_party_sigla'), 'party', ['sigla'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf_hash', sa.String(length=64), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_urna', sa.String(length=255), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('raca_cor', sa.String(length=50), nullable=True),
    sa.Column('escolaridade', sa.String(length=100), nullable=True),
    sa.Column('ocupacao', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_cpf_hash'), 'person', ['cpf_hash'], unique=True)
    op.create_index(op.f('ix_person_nome'), 'person', ['nome'], unique=False)
    op.create_index(op.f('ix_person_nome_urna'), 'person', ['nome_urna'], unique=False)
    op.create_table('territory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('codigo_ibge', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('populacao', sa.BigInteger(), nullable=True),
    sa.Column('eleitorado', sa.BigInteger(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territory_codigo_ibge'), 'territory', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_territory_nome'), 'territory', ['nome'], unique=False)
    op.create_index(op.f('ix_territory_uf'), 'territory', ['uf'], unique=False)
    op.create_table('census_sector',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('codigo_setor', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('populacao', sa.Integer(), nullable=True),
    sa.Column('domicilios', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_census_sector_codigo_setor'), 'census_sector', ['codigo_setor'], unique=True)
    op.create_index(op.f('ix_census_sector_territory_id'), 'census_sector', ['territory_id'], unique=False)
    op.create_table('dataset_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('nome_dataset', sa.String(length=255), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=True),
    sa.Column('data_ingestao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_publicacao_fonte', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_arquivo', sa.String(length=128), nullable=True),
    sa.Column('caminho_raw', sa.Text(), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('erros', sa.Text(), nullable=True),
    sa.Column('registros_inseridos', sa.Integer(), nullable=True),
    sa.Column('registros_atualizados', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_version_source_id'), 'dataset_version', ['source_id'], unique=False)
    op.create_table('polling_zone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('numero_zona', sa.Integer(), nullable=False),
    sa.Column('nome_municipio', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('territory_id', 'numero_zona', name='uq_zone_territory_numero')
    )
    op.create_index(op.f('ix_polling_zone_territory_id'), 'polling_zone', ['territory_id'], unique=False)
    op.create_table('candidacy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('numero_urna', sa.String(length=20), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=False),
    sa.Column('situacao_detalhada', sa.Text(), nullable=True),
    sa.Column('votos_totais', sa.BigInteger(), nullable=True),
    sa.Column('percentual_votos', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('bens_declarados_total', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('tse_sq_candidato', sa.String(length=50), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('ingestao_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tse_sq_candidato', 'election_id', name='uq_candidacy_tse_election')
    )
    op.create_index(op.f('ix_candidacy_election_id'), 'candidacy', ['election_id'], unique=False)
    op.create_index(op.f('ix_candidacy_office_id'), 'candidacy', ['office_id'], unique=False)
    op.create_index(op.f('ix_candidacy_party_id'), 'candidacy', ['party_id'], unique=False)
    op.create_index(op.f('ix_candidacy_person_id'), 'candidacy', ['person_id'], unique=False)
    op.create_index(op.f('ix_candidacy_situacao'), 'candidacy', ['situacao'], unique=False)
    op.create_index(op.f('ix_candidacy_territory_id'), 'candidacy', ['territory_id'], unique=False)
    op.create_index(op.f('ix_candidacy_tse_sq_candidato'), 'candidacy', ['tse_sq_candidato'], unique=False)
    op.create_table('demographic_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('populacao_total', sa.BigInteger(), nullable=True),
    sa.Column('proporcao_feminina', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('mediana_idade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('densidade_demografica', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('territory_id', 'ano_referencia', name='uq_demographic_territory_ano')
    )
    op.create_index(op.f('ix_demographic_snapshot_territory_id'), 'demographic_snapshot', ['territory_id'], unique=False)
    op.create_table('income_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('renda_media_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('renda_mediana_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proporcao_ate_1sm', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('proporcao_1a3sm', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('proporcao_acima_3sm', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('gini', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('territory_id', 'ano_referencia', name='uq_income_territory_ano')
    )
    op.create_index(op.f('ix_income_snapshot_territory_id'), 'income_snapshot', ['territory_id'], unique=False)
    op.create_table('polling_place',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('polling_zone_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['polling_zone_id'], ['polling_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polling_place_polling_zone_id'), 'polling_place', ['polling_zone_id'], unique=False)
    op.create_table('record_lineage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('tabela_destino', sa.String(length=100), nullable=False),
    sa.Column('registro_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_lineage_dataset_version_id'), 'record_lineage', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_record_lineage_tabela_destino'), 'record_lineage', ['tabela_destino'], unique=False)
    op.create_table('social_program_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=True),
    sa.Column('familias_cadunico', sa.BigInteger(), nullable=True),
    sa.Column('beneficiarios_bolsa_familia', sa.BigInteger(), nullable=True),
    sa.Column('valor_pago_bolsa_familia', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('e_ground_truth', sa.Boolean(), nullable=False),
    sa.Column('limitacao_nota', sa.Text(), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('territory_id', 'ano_referencia', 'mes_referencia', name='uq_social_territory_ano_mes')
    )
    op.create_index(op.f('ix_social_program_snapshot_territory_id'), 'social_program_snapshot', ['territory_id'], unique=False)
    op.create_table('turnout_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('polling_zone_id', sa.UUID(), nullable=True),
    sa.Column('aptos', sa.BigInteger(), nullable=False),
    sa.Column('comparecimento', sa.BigInteger(), nullable=False),
    sa.Column('abstencao', sa.BigInteger(), nullable=False),
    sa.Column('votos_brancos', sa.BigInteger(), nullable=True),
    sa.Column('votos_nulos', sa.BigInteger(), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['polling_zone_id'], ['polling_zone.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'territory_id', 'polling_zone_id', name='uq_turnout_election_territory_zone')
    )
    op.create_index(op.f('ix_turnout_summary_election_id'), 'turnout_summary', ['election_id'], unique=False)
    op.create_index(op.f('ix_turnout_summary_polling_zone_id'), 'turnout_summary', ['polling_zone_id'], unique=False)
    op.create_index(op.f('ix_turnout_summary_territory_id'), 'turnout_summary', ['territory_id'], unique=False)
    op.create_table('campaign_expense',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidacy_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cnpj_fornecedor', sa.String(length=20), nullable=True),
    sa.Column('nome_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('tse_seq_despesa', sa.String(length=50), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidacy_id'], ['candidacy.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_expense_candidacy_id'), 'campaign_expense', ['candidacy_id'], unique=False)
    op.create_index(op.f('ix_campaign_expense_tse_seq_despesa'), 'campaign_expense', ['tse_seq_despesa'], unique=False)
    op.create_table('campaign_revenue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidacy_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('origem', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cnpj_cpf_doador', sa.String(length=20), nullable=True),
    sa.Column('nome_doador', sa.String(length=255), nullable=True),
    sa.Column('tse_seq_receita', sa.String(length=50), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidacy_id'], ['candidacy.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_revenue_candidacy_id'), 'campaign_revenue', ['candidacy_id'], unique=False)
    op.create_index(op.f('ix_campaign_revenue_tse_seq_receita'), 'campaign_revenue', ['tse_seq_receita'], unique=False)
    op.create_table('polling_section',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('polling_place_id', sa.UUID(), nullable=False),
    sa.Column('numero_secao', sa.Integer(), nullable=False),
    sa.Column('eleitorado_aptos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['polling_place_id'], ['polling_place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polling_place_id', 'numero_secao', name='uq_section_place_numero')
    )
    op.create_index(op.f('ix_polling_section_polling_place_id'), 'polling_section', ['polling_place_id'], unique=False)
    op.create_table('vote_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidacy_id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('polling_zone_id', sa.UUID(), nullable=True),
    sa.Column('polling_section_id', sa.UUID(), nullable=True),
    sa.Column('votos', sa.BigInteger(), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidacy_id'], ['candidacy.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['polling_section_id'], ['polling_section.id'], ),
    sa.ForeignKeyConstraint(['polling_zone_id'], ['polling_zone.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidacy_id', 'territory_id', 'polling_zone_id', 'polling_section_id', name='uq_vote_result_candidacy_granularity')
    )
    op.create_index(op.f('ix_vote_result_candidacy_id'), 'vote_result', ['candidacy_id'], unique=False)
    op.create_index(op.f('ix_vote_result_election_id'), 'vote_result', ['election_id'], unique=False)
    op.create_index(op.f('ix_vote_result_polling_section_id'), 'vote_result', ['polling_section_id'], unique=False)
    op.create_index(op.f('ix_vote_result_polling_zone_id'), 'vote_result', ['polling_zone_id'], unique=False)
    op.create_index(op.f('ix_vote_result_territory_id'), 'vote_result', ['territory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_result_territory_id'), table_name='vote_result')
    op.drop_index(op.f('ix_vote_result_polling_zone_id'), table_name='vote_result')
    op.drop_index(op.f('ix_vote_result_polling_section_id'), table_name='vote_result')
    op.drop_index(op.f('ix_vote_result_election_id'), table_name='vote_result')
    op.drop_index(op.f('ix_vote_result_candidacy_id'), table_name='vote_result')
    op.drop_table('vote_result')
    op.drop_index(op.f('ix_polling_section_polling_place_id'), table_name='polling_section')
    op.drop_table('polling_section')
    op.drop_index(op.f('ix_campaign_revenue_tse_seq_receita'), table_name='campaign_revenue')
    op.drop_index(op.f('ix_campaign_revenue_candidacy_id'), table_name='campaign_revenue')
    op.drop_table('campaign_revenue')
    op.drop_index(op.f('ix_campaign_expense_tse_seq_despesa'), table_name='campaign_expense')
    op.drop_index(op.f('ix_campaign_expense_candidacy_id'), table_name='campaign_expense')
    op.drop_table('campaign_expense')
    op.drop_index(op.f('ix_turnout_summary_territory_id'), table_name='turnout_summary')
    op.drop_index(op.f('ix_turnout_summary_polling_zone_id'), table_name='turnout_summary')
    op.drop_index(op.f('ix_turnout_summary_election_id'), table_name='turnout_summary')
    op.drop_table('turnout_summary')
    op.drop_index(op.f('ix_social_program_snapshot_territory_id'), table_name='social_program_snapshot')
    op.drop_table('social_program_snapshot')
    op.drop_index(op.f('ix_record_lineage_tabela_destino'), table_name='record_lineage')
    op.drop_index(op.f('ix_record_lineage_dataset_version_id'), table_name='record_lineage')
    op.drop_table('record_lineage')
    op.drop_index(op.f('ix_polling_place_polling_zone_id'), table_name='polling_place')
    op.drop_table('polling_place')
    op.drop_index(op.f('ix_income_snapshot_territory_id'), table_name='income_snapshot')
    op.drop_table('income_snapshot')
    op.drop_index(op.f('ix_demographic_snapshot_territory_id'), table_name='demographic_snapshot')
    op.drop_table('demographic_snapshot')
    op.drop_index(op.f('ix_candidacy_tse_sq_candidato'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_territory_id'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_situacao'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_person_id'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_party_id'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_office_id'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_election_id'), table_name='candidacy')
    op.drop_table('candidacy')
    op.drop_index(op.f('ix_polling_zone_territory_id'), table_name='polling_zone')
    op.drop_table('polling_zone')
    op.drop_index(op.f('ix_dataset_version_source_id'), table_name='dataset_version')
    op.drop_table('dataset_version')
    op.drop_index(op.f('ix_census_sector_territory_id'), table_name='census_sector')
    op.drop_index(op.f('ix_census_sector_codigo_setor'), table_name='census_sector')
    op.drop_table('census_sector')
    op.drop_index(op.f('ix_territory_uf'), table_name='territory')
    op.drop_index(op.f('ix_territory_nome'), table_name='territory')
    op.drop_index(op.f('ix_territory_codigo_ibge'), table_name='territory')
    op.drop_table('territory')
    op.drop_index(op.f('ix_person_nome_urna'), table_name='person')
    op.drop_index(op.f('ix_person_nome'), table_name='person')
    op.drop_index(op.f('ix_person_cpf_hash'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_party_sigla'), table_name='party')
    op.drop_table('party')
    op.drop_table('office')
    op.drop_index(op.f('ix_election_ano'), table_name='election')
    op.drop_table('election')
    op.drop_table('data_source')
    # ### end Alembic commands ###
