"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, MapPinned, Target } from "lucide-react";
import { formatNumber, loadOfficialDataset, OfficialDataset } from "@/components/local/official-data";

type Plan = { priority: "alta" | "media" | "manutencao"; goal: string; action: string; reviewed: boolean };
const storageKey = "mapa-voto-territorial-plan-v1";
const blankPlan: Plan = { priority: "media", goal: "", action: "", reviewed: false };

export function StrategyBoard() {
  const [dataset, setDataset] = useState<OfficialDataset | null>(null);
  const [candidateId, setCandidateId] = useState("");
  const [plans, setPlans] = useState<Record<string, Plan>>({});
  const [error, setError] = useState("");
  useEffect(() => { try { setPlans(JSON.parse(localStorage.getItem(storageKey) || "{}")); } catch {} loadOfficialDataset().then((data) => { setDataset(data); setCandidateId(data.candidates[0]?.id || ""); }).catch((cause) => setError(cause.message)); }, []);
  const save = (code: string, changes: Partial<Plan>) => setPlans((current) => { const next = { ...current, [code]: { ...(current[code] || blankPlan), ...changes } }; localStorage.setItem(storageKey, JSON.stringify(next)); return next; });
  const territories = useMemo(() => dataset ? dataset.mapa.features.map((feature) => ({ code: feature.properties.codigo_ibge, name: feature.properties.nome, votes: feature.properties.votos[candidateId] || 0, total: feature.properties.total, plan: plans[feature.properties.codigo_ibge] || blankPlan })).filter((item) => item.votes > 0).sort((a, b) => b.votes - a.votes) : [], [candidateId, dataset, plans]);
  const configured = territories.filter((item) => item.plan.goal || item.plan.action).length;
  return <div><div className="page-header"><h1 style={{ display: "flex", alignItems: "center", gap: ".5rem" }}><Target size={28} style={{ color: "var(--accent)" }} /> Estratégia territorial</h1><p>Planejamento local baseado no resultado oficial. Metas e ações só aparecem depois que sua equipe as preenche.</p></div>
    {error ? <div className="card"><AlertCircle color="var(--warning)" /> {error}</div> : !dataset ? <div className="card">Carregando base oficial…</div> : <><div className="card" style={{ marginBottom: "1rem" }}><label className="field-label">Candidatura usada como referência<select className="input-field" value={candidateId} onChange={(event) => setCandidateId(event.target.value)}>{dataset.candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.nome} — {formatNumber(candidate.votos)} votos</option>)}</select></label></div><div className="grid-3" style={{ marginBottom: "1.5rem" }}><div className="stat-card"><div className="stat-label">Municípios com resultado</div><div className="stat-value">{territories.length}</div><div className="stat-sub">Base TSE 2022</div></div><div className="stat-card"><div className="stat-label">Planos preenchidos</div><div className="stat-value">{configured}</div><div className="stat-sub">Dados da sua equipe</div></div><div className="stat-card"><div className="stat-label">Itens revisados</div><div className="stat-value">{territories.filter((item) => item.plan.reviewed).length}</div><div className="stat-sub">Controle local</div></div></div><section className="card" style={{ padding: 0, overflow: "hidden" }}><div className="section-title" style={{ padding: "1rem" }}><MapPinned size={17} /> Plano por município</div><div style={{ overflowX: "auto" }}><table className="data-table"><thead><tr><th>Município</th><th style={{ textAlign: "right" }}>Votos 2022</th><th>Prioridade</th><th>Meta 2026</th><th>Próxima ação</th><th /></tr></thead><tbody>{territories.map((item) => <tr key={item.code}><td><strong>{item.name}</strong><span className="strategy-sub">{item.total ? `${((item.votes / item.total) * 100).toFixed(1)}% dos válidos locais` : ""}</span></td><td style={{ textAlign: "right" }}>{formatNumber(item.votes)}</td><td><select className="input-field" value={item.plan.priority} onChange={(event) => save(item.code, { priority: event.target.value as Plan["priority"] })}><option value="alta">Alta</option><option value="media">Média</option><option value="manutencao">Manutenção</option></select></td><td><input className="input-field" inputMode="numeric" placeholder="Definir" value={item.plan.goal} onChange={(event) => save(item.code, { goal: event.target.value })} /></td><td><input className="input-field" placeholder="Definir ação" value={item.plan.action} onChange={(event) => save(item.code, { action: event.target.value })} /></td><td><button className="btn btn-ghost btn-sm" onClick={() => save(item.code, { reviewed: !item.plan.reviewed })}>{item.plan.reviewed ? <><CheckCircle2 size={14} /> Revisado</> : "Revisar"}</button></td></tr>)}</tbody></table></div></section></>}</div>;
}
